### ISSUE TITLE
Sticky Headers not recognizing pinned SliverAppBar

### ISSUE THREAD

**Issue by leodr** [fluttercommunity/flutter_sticky_headers#10]
When using CustomScrollViews with a pinned SliverAppBar and a SliverList, the StickyHeader does not recognize the pinned SliverAppBar and just sticks underneath it, which obviously cannot be seen.

**Comment by anderha** [comment]
Same problem for me. Will this be fixed soon?

**Comment by anderha** [comment]
Found a solution:
1. use this package instead: https://pub.dartlang.org/packages/flutter_sticky_header
2. implementation as shown by @letsar https://gist.github.com/letsar/2e3cc98d328b3e84170abacf154e545f

**Comment by slightfoot** [comment]
Thanks for the reporting this. It is a known issue and myself and @letsar have been in talks to merge our repos. Parking this ticket until those talks are resolved.
