### ISSUE TITLE
There is a very fine line between the appbar and the sticky header.

### ISSUE THREAD

**Issue by DavidZXY** [fluttercommunity/flutter_sticky_headers#12]
![image](https://user-images.githubusercontent.com/23702287/50439180-08a8c500-092c-11e9-9523-4d54d99cc1d4.png)

**Comment by meodta** [comment]
Same Issue here, is there any chance that this will be solved anytime soon?

**Comment by slightfoot** [comment]
This is a floating point rounding error mixed with anti-aliasing. This is a platform issue. You can force the height of your AppBar or body to be an integer division of the devicePixelRatio will resolve this.

https://api.flutter.dev/flutter/widgets/MediaQueryData/devicePixelRatio.html
