### ISSUE TITLE
Question - Expansion tile like behaviour

### ISSUE THREAD

**Issue by kostaa** [fluttercommunity/flutter_sticky_headers#24]
How would one go about adding an expansion tile like behaviour so the children would expand/collapse similar to the Flutter [ExpansionTile](https://flutter.dev/docs/catalog/samples/expansion-tile-sample) behaviour?

**Comment by emvaized** [comment]
@kostaa 
[This](https://github.com/tp7309/flutter_sticky_and_expandable_list) new package can do that. 
However, without any animation yet.

**Comment by kostaa** [comment]
@emvaized Thanks for heads up!
There is  now support for animation - see the "CustomSectionAnimation Example".
