### ISSUE TITLE
Is there a way to have multiple content under one StickyHeader?

### ISSUE THREAD

**Issue by ctrinh98** [fluttercommunity/flutter_sticky_headers#3]
Is there a way to have more than one content for one `StickyHeader`?  

As of right now, I can only manage to get one `ListTile` widget underneath a `StickyHeader` widget. But I want to make a single `ListView` with two `StickyHeader` widgets and five `ListTile` widgets underneath each `StickyHeader` widget -- is that possible?

Thank you in advance @slightfoot for any help you can provide!

**Comment by ctrinh98** [comment]
Oh, I never thought about putting the `ListTile` widgets in a `Column` widget! Please, is there any disadvantage to putting `ListTile` widgets inside a `Column` widget and then putting that `Column` widget inside a `ListView` widget?

**Comment by tamoyal** [comment]
Won't `ListTile`s in the `Column` widget negatively affect performance on big lists and defeat the purpose of using the list view in the first place?

**Comment by dukaric1991** [comment]
I would like to have one header active over several listItems in ListView.builder. Is it possible?
January(HEADER1)
-January content --> HEADER1
-January content --> HEADER1
-January content --> HEADER1
February(HEADER2)
-February content --> HEADER2
-February content --> HEADER2
March(HEADER3)
-March content --> HEADER3
etc...

**Comment by ashihCT** [comment]
@tamoyal I agree, seems like a limitation of this design. I am guessing in instances where you don't have the entire dataset (e.g. lazy-loaded infinite scrolling), it would not work.

**Comment by tz182736** [comment]
possible to use **ListView** widget as content of StickyHeader ?? I've tested and not working.
```
 StickyHeader(
  header: Text("Header 1"),
  content: ListView(
    children: ...
))
```

**Comment by hehuapei** [comment]
> is it possible to use **ListView** widget as content of StickyHeader ??
> I've tested and not working.
> 
> ```
>  StickyHeader(
>   header: Text("Header 1"),
>   content: ListView(
>     children: ...
> ))
> ```



> is it possible to use **ListView** widget as content of StickyHeader ??
> I've tested and not working.
> 
> ```
>  StickyHeader(
>   header: Text("Header 1"),
>   content: ListView(
>     children: ...
> ))
> ```

I've tested. It works!

**Comment by hehuapei** [comment]
> is it possible to use **ListView** widget as content of StickyHeader ??
> I've tested and not working.
> 
> ```
>  StickyHeader(
>   header: Text("Header 1"),
>   content: ListView(
>     children: ...
> ))
> ```

I've tested. It works!

**Comment by alefcarlos** [comment]
@hehuapei I suppose @tz182736 said that when you use  StickyHeader in nested scrollable widgets. I had this problem too.

You need to set `shrinkWrap` to true, so this must work!

An example:

```dart
          child: ListView.builder(
            controller: _scrollController,
            itemCount: data.length,
            itemBuilder: (BuildContext context, int index) {
              var groupKey = data.keys.elementAt(index);

              return StickyHeader(
                header: Container(
                  height: 50.0,
                  color: Colors.blueGrey[700],
                  padding: EdgeInsets.symmetric(horizontal: 16.0),
                  alignment: Alignment.centerLeft,
                  child: Text(
                    '$groupKeyDescription - $eventCountDescription',
                    style: TextStyle(color: Colors.white),
                  ),
                ),
                content: ListView.builder(
                  physics: NeverScrollableScrollPhysics(),
                  itemCount: data[groupKey].length,
                  shrinkWrap: true,
                  itemBuilder: (BuildContext context, int index) {
                    var item = data[groupKey][index];

                    return ListTile(
                      leading: EventListItemAvatar(event: item),
                      isThreeLine: true,
                      title:
                          Text('${EventHelpers.eventTypeToString(item.type)}'),
                      subtitle: Text(
                          '${EventHelpers.loadTypeToString(item.loadType)} - ${item.itemsQuantity} itens\n${dateFormat.format(item.arrivedDate.toDate())}'),
                    );
                  },
                ),
              );
            },
          ),
```

I've set `physics` to `NeverScrollableScrollPhysics`, because I didnt want to make my items scrollable.

**Comment by slightfoot** [comment]
You should avoid putting ListView's inside ListView's. ListView itself is expensive, enabling shrinkWrap, practically turns the ListView into a Column. You'd be better of using a Column for this.

Check out this example.
```
child: ListView.builder(
  controller: _scrollController,
  itemCount: data.length,
  itemBuilder: (BuildContext context, int index) {
    var groupKey = data.keys.elementAt(index);
    return StickyHeader(
      header: Container(
        height: 50.0,
        color: Colors.blueGrey[700],
        padding: EdgeInsets.symmetric(horizontal: 16.0),
        alignment: Alignment.centerLeft,
        child: Text(
          '$groupKeyDescription - $eventCountDescription',
          style: TextStyle(color: Colors.white),
        ),
      ),
      content: Column(
        children: <Widget>[
          for(final item in data[groupKey])
            ListTile(
              leading: EventListItemAvatar(event: item),
              isThreeLine: true,
              title: Text('${EventHelpers.eventTypeToString(item.type)}'),
              subtitle: Text(
                '${EventHelpers.loadTypeToString(item.loadType)} - ${item.itemsQuantity} items\n${dateFormat.format(item.arrivedDate.toDate())}',
              ),
            ),
        ],
      ),
    );
  },
),
```

**Comment by alefcarlos** [comment]
But how about performance ? ListView guarantees only visible will be rendered, if I using Column all my items will be rendered. Column is the best option ?

**Comment by slightfoot** [comment]
@alefcarlos When you enable `shrinkWrap` it will make `ListView` render ALL items, just like a Column, but with more processing to achieve the same result. You'll still be best using a Column.

**Comment by alefcarlos** [comment]
Hum... I didn't know about that ! Thank you ! I'm gonna refactor my code. 😁

Em seg, 17 de jun de 2019 10:22, Simon Lightfoot <notifications@github.com>
escreveu:
