### ISSUE TITLE
Sticky header shake 

### ISSUE THREAD

**Issue by daveleenew** [fluttercommunity/flutter_sticky_headers#36]
When scrolling Sticky header shake.

**Comment by xiejibiao** [comment]
@daveleenew I also have this problem. Have you solved it?

**Comment by topjx** [comment]
@daveleenew I also have this problem. Have you solved it?

**Comment by JacksonHiew** [comment]
Just use `physics: ClampingScrollPhysics()`

**Comment by slightfoot** [comment]
Fixed as-of v0.3.0.

**Comment by azizswebni** [comment]
I'm facing the same problem even using version 0.3.0
