### ISSUE TITLE
Sticky Header Crash

### ISSUE THREAD

**Issue by xuhongfei** [fluttercommunity/flutter_sticky_headers#42]
<img width="826" alt="Screen Shot 2020-10-29 at 07 11 04" src="https://user-images.githubusercontent.com/3990919/97506483-fe3b3480-19b5-11eb-8d47-7b49638bac08.png">

<img width="1122" alt="Screen Shot 2020-10-29 at 07 27 12" src="https://user-images.githubusercontent.com/3990919/97507564-668b1580-19b8-11eb-9958-8ea26c11f586.png">

<img width="819" alt="Screen Shot 2020-10-29 at 07 15 36" src="https://user-images.githubusercontent.com/3990919/97506830-d26c7e80-19b6-11eb-8fa5-537aff3f5d87.png">

**if `itemCount` set to 2, will cause crash.**

```dart
Widget _buildBody(BuildContext context) {
    return ListView.builder(
      controller: _scrollController,
      physics: BouncingScrollPhysics(),
      itemCount: 2,
      itemBuilder: (context, index) {
        return StickyHeader(
          overlapHeaders: true,
          header: Container(
            height: 50.0,
            color: MyColors.lightGrayColor,
            padding: EdgeInsets.symmetric(horizontal: 16.0),
            alignment: Alignment.centerLeft,
            child: Text('Header #$index',
              style: const TextStyle(color: Colors.white),
            ),
          ),
          content: _buildContent(context),
        );
      },
    );
  }

  Widget _buildContent(BuildContext context) {
    return GridView.builder(
      controller: _scrollController,
      shrinkWrap: true,
      physics: BouncingScrollPhysics(),
      itemCount: 30,
      gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 2,
        mainAxisSpacing: 1,
        crossAxisSpacing: 1,
        childAspectRatio: 1,
      ), 
      itemBuilder: (BuildContext context, int index) {
        return Container(
          height: 44,
          color: MyColors.backgroundColor,
          child: Text(index.toString()),
        );
      },
    );
  }
```

@brianegan , pls help to check this crash. Thanks a lot!

**Comment by xuhongfei** [comment]
+ @jeroen-meijer

**Comment by NiklaesAtShortcut** [comment]
I am facing the same issue.

**Comment by DeD1rk** [comment]
I used to get the same issue (note that is was only a silent/caught exception, which is annoying while debugging but not a 'crash') as of flutter 2.2.3, but it seems that it no longer occurs in flutter 2.5.0.

**Comment by slightfoot** [comment]
Cannot replicate this issue from the example above on Flutter 3.0.0. Please retest. I also noticed your using the same controller in both ListView and GridView widgets and that can cause an issue.
