### ISSUE TITLE
pull to refresh

### ISSUE THREAD

**Issue by Sabirjan** [fluttercommunity/flutter_sticky_headers#49]
pull to refresh

**Comment by DeD1rk** [comment]
Pull to refresh can be implemented by simply surrounding a scrollable widget in a `RefreshIndicator`. The flutter documentation can guide you further for that. I don't think that the sticky_headers package should have anything to do with pull to refresh, so this issue can probably be closed.

**Comment by slightfoot** [comment]
Closing as un-responsive.
