### ISSUE TITLE
A ScrollPositionWithSingleContext was used after being disposed.

### ISSUE THREAD

**Issue by topjx** [fluttercommunity/flutter_sticky_headers#51]
The following assertion was thrown building RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#bc1b8](state: RawGestureDetectorState#1c9cc(gestures: [vertical drag], behavior: opaque)):
A ScrollPositionWithSingleContext was used after being disposed.

Once you have called dispose() on a ScrollPositionWithSingleContext, it can no longer be used.
The relevant error-causing widget was:

**Comment by DeD1rk** [comment]
Please provide additional context, such as a code sample (preferably something we can run), version info, and a more complete error (include for example the complete message and stack trace).

**Comment by slightfoot** [comment]
Closing as un-responsive.
