### ISSUE TITLE
dependency doesn't support null safety

### ISSUE THREAD

**Issue by ibrahimxcool** [fluttercommunity/flutter_sticky_headers#53]
```
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

- package:sticky_headers
```

**Comment by DeD1rk** [comment]
Please add some additional context, such as version numbers and the output from `flutter doctor`. Sticky headers version `0.2.0` does support null safety, so you'll probably want to specify `sticky_headers: ^0.2.0` in your `pubspec.yaml`.

**Comment by tusharkhatriofficial** [comment]
run your app with 
`flutter run --no-sound-null-safety`
and build with
` flutter build apk --release --no-sound-null-safety`
and If you are using Android studio then go to configuration and add `--no-sound-null-safety` in **additional run args**

**Comment by tusharkhatriofficial** [comment]
Or if you don't want to do this then just remove this dependency and add only those dependencies which support null safety.

**Comment by slightfoot** [comment]
The package is now null-safe as of 0.2.0. Closing.
