### ISSUE TITLE
Unhandled exception:  setState() called after dispose()

### ISSUE THREAD

**Issue by marcglasberg** [fluttercommunity/flutter_sticky_headers#6]
Simon, I get this if I scroll the list fast enough:

    Unhandled exception:
    E/flutter ( 4840): setState() called after dispose(): _StickyHeaderBuilderState#2ad9c(lifecycle state: defunct, not mounted)
    _StickyHeaderBuilderState.build.<anonymous closure>.<anonymous closure> (package:sticky_headers/sticky_headers/widget.dart:121:58)

It tells me this:

    *This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback. The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter ( 4840): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().*

I believe the item is being removed from the tree (because of scrolling) before the next frame is displayed.

**Comment by filly82** [comment]
got the same error. did you solve your problem @marcglasberg ?

**Comment by marcglasberg** [comment]
No, I didn't.

**Comment by ldsenow** [comment]
I have the same error and it looks like no one is maintaining the project atm.

**Comment by slightfoot** [comment]
This is resolved as of `v0.1.8`
