### ISSUE TITLE
gridview line header

### ISSUE THREAD

**Issue by yagizdo** [fluttercommunity/flutter_sticky_headers#62]
Hello. I have one gridview. I am listing 3 pictures per line. I want to put a title on those 3 pictures. I tried an example like in the picture, but it put the whole list. If I just wrap the cachedimagenetwork, this time it adds a title to each image.

I want a title for every line, that is, every 3 pictures. You can see my list from the design in the example I posted. 

I searched a lot but couldn't find anything about wrapping the line. Do you have any suggestions?

Thanks in advance.

![image](https://user-images.githubusercontent.com/31064552/168322410-607dedb6-5710-477c-ac08-fc609fe3cdfa.png)

**Comment by slightfoot** [comment]
You need to post your code or even better a link to your repo and not a image. It is also unclear what you are asking. 

If you want a StickyHeader for every row of 3 items.. you can just do that.. You should NOT use a GridView but a Row() with Expanded as the children.

**Comment by slightfoot** [comment]
Perhaps come ask on HumpdayQandA every Wednesday on YouTube where we answer peoples Flutter questions. 
https://www.youtube.com/c/FlutterCommunityVideos
https://twitter.com/FlutterComm

**Comment by yagizdo** [comment]
> You need to post your code or even better a link to your repo and not a image. It is also unclear what you are asking.
> 
> If you want a StickyHeader for every row of 3 items.. you can just do that.. You should NOT use a GridView but a Row() with Expanded as the children.

How is it not clear what I am asking? In addition, my codes are also visible in the picture. And I already tried the solution you suggested before posting it here :D
