### ISSUE TITLE
[BUG] StickyHeader not working inside a CustomScrollView

### ISSUE THREAD

**Issue by Areopagitics** [fluttercommunity/flutter_sticky_headers#65]
I get the following error when trying to use a **StickyHeader** inside a **CustomScrollView**:

> A RenderViewport expected a child of type RenderSliver but received a child of type RenderStickyHeader

It seems to be misleading that the top of the README for the package states:

> You can place a StickyHeader or StickyHeaderBuilder inside any scrollable content, such as: ListView, GridView, **CustomScrollView**, SingleChildScrollView or similar.

**Comment by 13protons** [comment]
FWIW, this works fine for me when the StickyHeader is inside a SliverList's delegate. The sticky header returns a BoxWidget, so can't be a direct child of CustomScrollView.

**Comment by Areopagitics** [comment]
Good to know! Thanks!

**Comment by Pranoy1c** [comment]
@13protons Can you give an example of that?

My SliverList's delegate returns `SliverChildBuilderDelegate`. Where would I put the StickyHeader?
