### ISSUE TITLE
Shadow when header is overlapping content?

### ISSUE THREAD

**Issue by rchampeaux** [fluttercommunity/flutter_sticky_headers#7]
It would be nice if there was a slight shadow when the content scrolls under the sticky header.

So, as a sticky header scrolls up to the top, it's at the same elevation as the content and casts no shadow, but when it sticks at the top and the content scrolls under it, it should raise in elevation and a slight shadow should be displayed. 

The previous top header that is being pushed off should be at the same elevation as the new header and should not cast a shadow on the new header that is pushing it off.

Bonus points for letting me specify the elevation and thus the shadow depth.

**Comment by emvaized** [comment]
I implemented it this way:

```
StickyHeaderBuilder(
        builder: (BuildContext context, double stickiness) {
           return Card(
             elevation: stickiness < 0.0 ? 3 : 0,
             child: Container()
           );
         },
        content: Container()
         );
```
